[package]
name = "advent_of_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
lazy_static = "1.4.0"
iter_tools = "0.1.4"
regex = "1.7.0"
nom = "7.1.1"
